language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
services:
  - docker

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

install: composer install --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml.dist

before_deploy:
  - curl -LSs http://box-project.github.io/box2/installer.php | php
  - php box.phar build

deploy:
  provider: releases
  api_key:
    secure: R18a+x1dIMitk7Aq5WgqDS6izrgcgAcpuqo7AqJk8RuoBqrRLT36GlKrnDSKDSI71U18CQJXmfDBeI4q3R0BD+zJJ/W9uv9g25YFlbFhdAyBlwdC7GRod+XreUOQGRDBj8PpywmxCKZrKlhftu1Yw+9p3ezDcHyQMnaUODmh11Mn2UpX1AxJePSKcsh01hbyXzKmjiyV4TBXhhEAW3diONuGVTgou5OES2925REmoD5tEMKEhS8gQ9Z2fQGNlCjYh6rkX/N2oY6zgs9zrNCEmfvaAHfsPkmnlvwsQPmRXW5PH/bBGIRFpotsIFOkeZurwpy5OkwoiV2Revxbm4sivcV9ogxRHt+MhsbQZOGmsGKvc4JtGU9gy8LGxnJXyfcKhw/gGVRXeBikZeGbnG1C8qisFBIouK7wtRb6F/qsuXMb5l4nbKaUTFM3dg8yaEygbp9vEsCShaH149gFGaAChJvSOsdDUr4/bCCDaEDhAdV+bcIjMexDd79UHOrddE0B6EWGctXzWRzn495oz1we/7B7CmFZ0wzfMjDeysukFQj7GZTFPwWIHiXMKpCiDQc9w+rWjqh3DFwNmqa8eH+hGQRQ8Dl7TpoE1ucUZQwpSiF0ES1MYlcK66bteAPolQp8Iux1IIMOBsQ2VBmxjajMXTu6ZDvrD3l8il4SE+E6QT8=
  file: bin/docker-hostmanager.phar
  on:
    repo: vojtabiberle/docker-hostmanager

after_deploy:
  - docker build -t vojtabiberle/docker-hostmanager .
  - docker_push.sh