language: php
sudo: false
php:
  - 7.2
services:
  - docker

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

install: composer install --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml.dist

before_deploy:
  - curl -LSs http://box-project.github.io/box2/installer.php | php
  - php box.phar build

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: bin/docker-hostmanager.phar
  on:
    repo: vojtabiberle/docker-hostmanager

after_deploy:
  - docker build -t vojtabiberle/docker-hostmanager .
  - docker_push.sh